### ISSUE TITLE
Evaluation measures: Slot error rates

### ISSUE THREAD

**Issue by simon-clematide** [impresso/CLEF-HIPE-2020-scorer#3]
@maud What would be the expected benefits for this evaluation if we 
 - already do entity-level evaluations (not IOB-token-level evaluations)?
 - allow fuzzy matches?

paper: https://pdfs.semanticscholar.org/451b/61b390b86ae5629a21461d4c619ea34046e0.pdf

**Comment by mromanello** [comment]
can be closed
